"""Test the ONNX audio detector on real-world human speech and real computer TTS speech."""
import os, sys
import subprocess
import librosa
import numpy as np
import onnxruntime as ort

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

os.makedirs('data', exist_ok=True)

# 1. Generate real TTS speech via PowerShell SAPI
tts_wav = 'data/tts_sample.wav'
cmd = "Add-Type -AssemblyName System.Speech; $s = New-Object System.Speech.Synthesis.SpeechSynthesizer; $s.SetOutputToWaveFile('data/tts_sample.wav'); $s.Speak('This is an automated voice test generated by a computer text to speech system for verifying deepfakes.'); $s.Dispose()"
subprocess.run(["powershell", "-NoProfile", "-Command", cmd], check=True)

# Load ONNX sessions
sess_pre = ort.InferenceSession('models/audio/preproc.onnx', providers=['CPUExecutionProvider'])
sess_cnn = ort.InferenceSession('models/audio/audio_detector.onnx', providers=['CPUExecutionProvider'])

def evaluate(wav_path, label):
    y, _ = librosa.load(wav_path, sr=16000, mono=True)
    y3 = y[:48000] if len(y) >= 48000 else np.pad(y, (0, 48000 - len(y)))
    img = sess_pre.run(None, {'audio': y3[None, :].astype(np.float32)})[0]
    out = sess_cnn.run(None, {sess_cnn.get_inputs()[0].name: img})[0]
    exp = np.exp(out - np.max(out))
    probs = exp / np.sum(exp)
    p_fake, p_real = float(probs[0, 0]), float(probs[0, 1])
    verdict = 'REAL' if p_real > p_fake else 'FAKE'
    correct = (verdict == label)
    status = "✅ PASS" if correct else "❌ FAIL"
    print(f"[{status}] {os.path.basename(wav_path):<30} | Ground Truth: {label:<4} -> Pred: {verdict:<4} (Real: {p_real*100:5.1f}%, Fake: {p_fake*100:5.1f}%)")

print("=" * 80)
print("  EVALUATION ON OUT-OF-DISTRIBUTION / REAL-WORLD AUDIO SAMPLES")
print("=" * 80)

# Real Human Voice 1 (LibriSpeech clean reader)
libri_path = librosa.ex('libri1')
evaluate(libri_path, 'REAL')

# Real Human Voice 2 (Brahms orchestra/acoustic sample from librosa)
brahms_path = librosa.ex('brahms')
evaluate(brahms_path, 'REAL')

# Real Computer TTS Voice (Windows SAPI synthesizer)
evaluate(tts_wav, 'FAKE')
print("=" * 80)
